version: '3.1'
services:
  web_dev:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./extra-addons:/mnt/extra-addons
    # si no especifico un environment se toma el de odoo:16.0 que es el db_host=db y no puedo cambiar su nombre
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"